mqtt:
  host: 127.0.0.1
  port: 1883
  sensor_topic_root: purpleair2mqtt
  status_topic: alerts/purpleair2mqtt/status

purple_air:
  urls:
    - http://192.168.0.245/json?live=true
  refresh_interval_seconds: 300

home_assistant:
  discovery_prefix: homeassistant
  discovery_enabled: true

logging:
  level: DEBUG
  path: "./logs/purpleair2mqtt.log"
  max_keep: 10